//
//  MerchantItem.swift
//  YZB_Company
//
//  Created by Mac on 16.09.2019.
//  Copyright © 2019 WZKJ. All rights reserved.
//

import Foundation
import ObjectMapper

class MerchantItem: NSObject, Mappable {
    
    var id : String? //  "8F4772F0D338483C9C40DA824F026022",
    var isNewRecord : String? //  false,
    var remarks : String? //  null,
    var createBy : String? //  null,
    var createDate : String? //  null,
    var updateBy : String? //  null,
    var updateDate : String? //  null,
    var delFlag : String? //  "0",
    var merchantNo : String? //  null,
    var userName : String? //  null,
    var type : String? //  null,
    var password : String? //  null,
    var realName : String? //  null,
    var mobile : String? //  null,
    var email : String? //  null,
    var qq : String? //  null,
    var headUrl : String? //  null,
    var personal : String? //  null,
    var prov : String? //  null,
    var city : String? //  null,
    var dist : String? //  null,
    var address : String? //  null,
    var longitude : String? //  null,
    var latitude : String? //  null,
    var vol : String? //  null,
    var evaluate : String? //  null,
    var evaluateScore : String? //  null,
    var regIp : String? //  null,
    var lastLoginTime : String? //  null,
    var lastLoginIp : String? //  null,
    var isActive : String? //  null,
    var category : String? //  null,
    var idCard : String? //  null,
    var idcardpicUrlF : String? //  null,
    var idcardpicUrlB : String? //  null,
    var devicename : String? //  null,
    var appversion : String? //  null,
    var devicetype : String? //  null,
    var devicesystem : String? //  null,
    var size : String? //  null,
    var certpicCert : String? //  null,
    var certCode : String? //  null,
    var wechat : String? //  null,
    var startDate : String? //  null,
    var brandName : String? //  null,
    var brandId : String? //  null,
    var name : String? //  "贝朗（中国）卫浴有限公司",
    var contacts : String? //  null,
    var contactsTel : String? //  null,
    var money : String? //  null,
    var safepassword : String? //  null,
    var servicephone : String? //  null,
    var brand : String? //  null,
    var categoryId : String? //  null,
    var newPassword : String? //  null,
    var passOn : String? //  null,
    var ishide : String? //  2,
    var isshow : String? //  null,
    var logoUrl : String? //  null,
    var substationId : String? //  "",
    var legalRepresentative : String? //  null,
    var businessScope : String? //  null,
    var registeredCapital : String? //  null,
    var businessTermStart : String? //  null,
    var businessTermEnd : String? //  null
    
    required init?(map: Map) {
        
    }
    
    func mapping(map: Map) {
        
        id <- map["id"] //String? //  "8F4772F0D338483C9C40DA824F026022",
        isNewRecord <- map["isNewRecord"] //String? //  false,
        remarks <- map["merchant"] //String? //  null,
        createBy <- map["createBy"] //String? //  null,
        createDate <- map["createDate"] //String? //  null,
        updateBy <- map["updateBy"] //String? //  null,
        updateDate <- map["updateDate"] //String? //  null,
        delFlag <- map["delFlag"] //String? //  "0",
        merchantNo <- map["merchantNo"] //String? //  null,
        userName <- map["userName"] //String? //  null,
        type <- map["merchant"] //String? //  null,
        password <- map["password"] //String? //  null,
        realName <- map["realName"] //String? //  null,
        mobile <- map["mobile"] //String? //  null,
        email <- map["email"] //String? //  null,
        qq <- map["qq"] //String? //  null,
        headUrl <- map["merchant"] //String? //  null,
        personal <- map["personal"] //String? //  null,
        prov <- map["prov"] //String? //  null,
        city <- map["city"] //String? //  null,
        dist <- map["dist"] //String? //  null,
        address <- map["address"] //String? //  null,
        longitude <- map["merchant"] //String? //  null,
        latitude <- map["latitude"] //String? //  null,
        vol <- map["vol"] //String? //  null,
        evaluate <- map["evaluate"] //String? //  null,
        evaluateScore <- map["evaluateScore"] //String? //  null,
        regIp <- map["regIp"] //String? //  null,
        lastLoginTime <- map["lastLoginTime"] //String? //  null,
        lastLoginIp <- map["lastLoginIp"] //String? //  null,
        isActive <- map["isActive"] //String? //  null,
        category <- map["category"] //String? //  null,
        idCard <- map["idCard"] //String? //  null,
        idcardpicUrlF <- map["idcardpicUrlF"] //String? //  null,
        idcardpicUrlB <- map["idcardpicUrlB"] //String? //  null,
        devicename <- map["devicename"] //String? //  null,
        appversion <- map["appversion"] //String? //  null,
        devicetype <- map["devicetype"] //String? //  null,
        devicesystem <- map["devicesystem"] //String? //  null,
        size <- map["size"] //String? //  null,
        certpicCert <- map["certpicCert"] //String? //  null,
        certCode <- map["certCode"] //String? //  null,
        wechat <- map["wechat"] //String? //  null,
        startDate <- map["startDate"] //String? //  null,
        brandName <- map["brandName"] //String? //  null,
        brandId <- map["brandId"] //String? //  null,
        name <- map["name"] //String? //  "贝朗（中国）卫浴有限公司",
        contacts <- map["contacts"] //String? //  null,
        contactsTel <- map["contactsTel"] //String? //  null,
        money <- map["money"] //String? //  null,
        safepassword <- map["safepassword"] //String? //  null,
        servicephone <- map["servicephone"] //String? //  null,
        brand <- map["brand"] //String? //  null,
        categoryId <- map["categoryId"] //String? //  null,
        newPassword <- map["newPassword"] //String? //  null,
        passOn <- map["passOn"] //String? //  null,
        ishide <- map["ishide"] //String? //  2,
        isshow <- map["merchant"] //String? //  null,
        logoUrl <- map["logoUrl"] //String? //  null,
        substationId <- map["substationId"] //String? //  "",
        legalRepresentative <- map["legalRepresentative"] //String? //  null,
        businessScope <- map["merchant"] //String? //  null,
        registeredCapital <- map["registeredCapital"] //String? //  null,
        businessTermStart <- map["businessTermStart"] //String? //  null,
        businessTermEnd <- map["businessTermEnd"] //String? //  null
    }
}
