-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgTls8+3WINK9flOz0
H8hbptzIFHi4RWTnWhBoBhzpA8GgCgYIKoZIzj0DAQehRANCAAQfkewf8usyEHZA
LtvMGMDdFCAijMBAtvQ/K1y2eCuNczSN6Xpr+spUmA4+X/kvbD7KiuK4022/qjmt
L6XgVKg6
-----END PRIVATE KEY-----