-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgmsVbYcIIWYLnAE9/
9WJMKoStMykPYpllmDMIIICxfgSgCgYIKoZIzj0DAQehRANCAASsWUCyk4V7Sp9F
P+v6EISPxWiEmJajiPNrZTimACn425nFZi5OhJgg4sdbQyiCWMjMz8jTu4o42Khy
AEhZyeSf
-----END PRIVATE KEY-----